{
  "comments": [
    {
      "key": {
        "uuid": "9a3d3df0_ec14604e",
        "filename": "dovetail/testcase/sdnvpn.tempest-api.yml",
        "patchSetId": 1
      },
      "lineNbr": 10,
      "author": {
        "id": 5469
      },
      "writtenOn": "2018-02-05T06:58:57Z",
      "side": 1,
      "message": "The path here is \u0027/usr/lib/python2.7\u0027 not /usr/local/lib/python2.7",
      "range": {
        "startLine": 10,
        "startChar": 17,
        "endLine": 10,
        "endChar": 32
      },
      "revId": "7c7d4b4503569ed7c2856ec902568307be91eb98",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}